### ISSUE TITLE
Admin Order View cannot be opened when Postal Code is missing

### ISSUE THREAD

**Issue by HenKun** [netresearch/dhl-shipping-m2#26]
## Preconditions

- Magento 2.4.1
- dhl/module-shipping-core 1.1.2

## Steps to reproduce

- Create an order without postal code
  - Either create an order for a country where postal code is not required (`general/country/optional_zip_countries`)
  - Or create normal order and remove postal code from shipping address afterwards
- Visit admin order details page for this order

## Expected Result

- Order Details page is shown

## Actual Result

- Error on page:
```
TypeError: Argument 3 passed to Dhl\ShippingCore\Model\ShippingSettings\Processor\Checkout\ServiceOptions\RouteProcessor::process() must be of the type string, null given, called in /home/cloudpanel/htdocs/nebelkind.dev/vendor/dhl/module-shipping-core/Model/ShippingSettings/Processor/Packaging/PackagingDataCompositeProcessor.php on line 173 and defined in /home/cloudpanel/htdocs/nebelkind.dev/vendor/dhl/module-shipping-core/Model/ShippingSettings/Processor/Checkout/ServiceOptions/RouteProcessor.php:48
Stack trace: 
#0 /home/cloudpanel/htdocs/nebelkind.dev/vendor/dhl/module-shipping-core/Model/ShippingSettings/Processor/Packaging/PackagingDataCompositeProcessor.php(173): Dhl\ShippingCore\Model\ShippingSettings\Processor\Checkout\ServiceOptions\RouteProcessor->process()  
#1 /home/cloudpanel/htdocs/nebelkind.dev/vendor/dhl/module-shipping-core/Model/ShippingSettings/Processor/Packaging/PackagingDataCompositeProcessor.php(111): Dhl\ShippingCore\Model\ShippingSettings\Processor\Packaging\PackagingDataCompositeProcessor->processPackageOptions() #2 /home/cloudpanel/htdocs/nebelkind.dev/vendor/dhl/module-shipping-core/Model/ShippingSettings/PackagingDataProvider.php(84): Dhl\ShippingCore\Model\ShippingSettings\Processor\Packaging\PackagingDataCompositeProcessor->process()  
#3 /home/cloudpanel/htdocs/nebelkind.dev/vendor/dhl/module-shipping-core/Model/ShippingSettings/OrderDataProvider.php(48): Dhl\ShippingCore\Model\ShippingSettings\PackagingDataProvider->getData()  
#4 /home/cloudpanel/htdocs/nebelkind.dev/vendor/dhl/module-ui/ViewModel/Order/Info/ShippingServices.php(275): Dhl\ShippingCore\Model\ShippingSettings\OrderDataProvider->getShippingOptions()  
#5 /home/cloudpanel/htdocs/nebelkind.dev/vendor/dhl/module-ui/ViewModel/Order/Info/ShippingServices.php(98): Dhl\Ui\ViewModel\Order\Info\ShippingServices->getServiceOptions()  
#6 /home/cloudpanel/htdocs/nebelkind.dev/vendor/dhl/module-ui/view/base/templates/order/view/info/shipping-services.phtml(7): Dhl\Ui\ViewModel\Order\Info\ShippingServices->getSelectedServices()
```

## Possible Solution

`Dhl\ShippingCore\Model\ShippingSettings\Processor\Checkout\ServiceOptions\RouteProcessor::process()` requires `$postalCode` to be a string, whereas it could be also null. `$postalCode` can be made optional, it isn't even used in the method body.

```
    public function process(
        array $optionsData,
        string $countryId,
        string $postalCode,
        int $scopeId = null
    ): array {
```

**Comment by mam08ixo** [comment]
Acknowledged, thanks.

The Magento address entity is annotated to return the postcode as string but it does not.

https://github.com/magento/magento2/blob/2.4.1/app/code/Magento/Sales/Api/Data/OrderAddressInterface.php#L248-L253

We will work around that issue in the next release.
